### ISSUE TITLE
Bad path concatenation on Windows with Gulp 4

### ISSUE THREAD

**Issue by isochronous** [mauricedb/gulp-main-bower-files#63]
Using Gulp 4 and v1.6.2 of gulp-main-bower-files, I get the following error when calling this plugin: 

```
[15:29:31] Error: Bower components directory does not exist at C:\Projects\AI\main\Web\source\Ai.Web.Sitebower_components
    at Error (native)
    at module.exports (C:\Projects\AI\main\Web\source\Ai.Web.Site\node_modules\gulp-main-bower-files\node_modules\main-bower-files\lib\index.js:76:17)
    at DestroyableTransform._transform (C:\Projects\AI\main\Web\source\Ai.Web.Site\node_modules\gulp-main-bower-files\index.js:56:29)
    at DestroyableTransform.Transform._read (C:\Projects\AI\main\Web\source\Ai.Web.Site\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (C:\Projects\AI\main\Web\source\Ai.Web.Site\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Projects\AI\main\Web\source\Ai.Web.Site\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Projects\AI\main\Web\source\Ai.Web.Site\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (C:\Projects\AI\main\Web\source\Ai.Web.Site\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at DestroyableTransform.ondata (C:\Projects\AI\main\Web\source\Ai.Web.Site\node_modules\readable-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
```

Notice the `Ai.Web.Sitebower_components`, which should be `Ai.Web.Site\bower_components`.

I was able to work around this by adding a .bowerrc file and specifying `directory: '/bower_components'`, but that's introduced a new set of problems.

**Comment by isochronous** [comment]
Actually, on closer inspection, it seems like this plugin isn't really doing anything despite the lack of an error. The destination directory winds up being completely empty.

**Comment by mauricedb** [comment]
Hi @isochronous, 

Do you have a small repro with `bower.json`, expected and observed results for me to test this?

Did you by any change also try with **main-bower-files** directly and if so what was the result?

Maurice

**Comment by isochronous** [comment]
No, the only example I have right now is on a large, proprietary code base.  I can give you the important bits though.

Gulp task: 
```js
 return gulp.src("./bower.json")
 	.pipe(plugins.mainBowerFiles())
 	.pipe(gulp.dest("./ui/lib"));
```

.bowerrc contents
```js
{
    "directory": "bower_components",
    "strict-ssl": false,
    "https-proxy": ""
}
```

Bower.json file: https://gist.github.com/isochronous/cd4a15c39a7f371f66a199333fc274b2

Expected result: The main files (and files specified in the overrides in bower.json) should be copied to the `/ui/lib` folder of the project.

Observed result: The error from the original post.  Nothing gets copied to /ui/lib.  If I change the "directory" property in .bowerrc to `/bower_components` then I no longer get an error, but the main files are copied to a `bower_components` folder on the root of the drive due to the leading slash.

I did also try with main-bower-files and that worked just fine.

Updated gulp task:
```js
        return gulp.src(plugins.mainBowerFiles(), {
            base: './bower_components'
        }).pipe(gulp.dest('./ui/lib'));
```

**Comment by mauricedb** [comment]
Hi @isochronous,

I created a small sample based on the info provided and it seems to work just fine.

One thing I noticed in your `Gulpfile.js` snippet:
```
 return gulp.src("./bower.json")
 	.pipe(plugins.mainBowerFiles())
 	.pipe(gulp.dest("./ui/lib"));
```
It looks like you are calling **main-bower-files** instead of **gulp-main-bower-files**. I think the code should be as follows calling `plugins.gulpMainBowerFiles()`
```
 return gulp.src("./bower.json")
 	.pipe(plugins.gulpMainBowerFiles())
 	.pipe(gulp.dest("./ui/lib"));
```

Maurice

**Comment by isochronous** [comment]
That's because the gulp-plugins module automatically munges the names of
any packages that start with "gulp-". Sorry for the late reply, I don't
really monitor this email address much anymore.

**Comment by adamfriedland** [comment]
I've also experienced this same issue after the upgrade to Gulp 4 and using the latest version ofgulp-main-bower-files.
